apiVersion: 1

policies:
  - orgId: 1
    receiver: Amonora Control Telegram
    group_by:
      - grafana_folder
      - alertname
      - alert_class
    group_wait: 30s
    group_interval: 10m
    repeat_interval: 4h
    routes:
      - receiver: Amonora Control Telegram
        object_matchers:
          - ["severity", "=", "critical"]
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 2h
      - receiver: Amonora Control Telegram
        object_matchers:
          - ["alert_class", "=", "growth"]
        group_wait: 45s
        group_interval: 20m
        repeat_interval: 6h
