apiVersion: 1

contactPoints:
  - orgId: 1
    name: Amonora Control Telegram
    receivers:
      - uid: amonora-control-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: $__env{GRAFANA_ALERTS_WEBHOOK_URL}
          httpMethod: POST
          maxAlerts: 10
